name: curbwheel
description: Mobile application for the SharedStreets CurbWheel

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.61+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  moor_flutter:
  provider:
  chopper: ^2.0.0
  path: ^1.7.0
  turf: 
    git:
      url: git://github.com/dartclub/turf_dart.git
      ref: master
  qr_code_scanner: ^0.3.0
  path_provider:
  shared_preferences: '>=0.5.0 <2.0.0'
  flutter_svg: 0.19.3
  rxdart:
  flutter_blue: ^0.7.3
  mapbox_gl: ^0.9.0
  r_tree: ^1.1.0
  location: ^3.2.4
  synchronized: ^2.2.0+2
  uuid: 2.2.2
  camera:
  sentry_flutter: ^4.0.4
  progresso: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  build_runner:
  chopper_generator: ^2.0.0
  flutter_driver:
    sdk: flutter
  test: any
  json_serializable:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          weight: 300
        - asset: fonts/Raleway-Bold.ttf
          weight: 400
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
